version: "3.9" # optional since v1.27.0
services:
  # redis:
  #   image: redis
  #   command: redis-server
  db:
    image: postgres:13.3
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env
  api:
    build:
      context: ./back-end
      dockerfile: ./Dockerfile
    restart: always
    command: bash -c "cd api/back-end && python3 manage.py wait_for_database && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:3000"
    # command: bash -c "cd api/back-end && python3 && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:3000"
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      - .:/api
    depends_on:
      - db
  web:
    build: ./front-end
    image: node:14
    command: bash -c "cd web/front-end && yarn && yarn start"
    ports:
      - "3001:3000"
    volumes:
      - .:/web
    depends_on:
      - api
