# Generated by Django 3.2.6 on 2021-08-15 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_doc', models.FileField(blank=True, default='', upload_to='uploads/receipts/')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_row', models.IntegerField()),
                ('begin_col', models.IntegerField()),
                ('end_row', models.IntegerField()),
                ('end_col', models.IntegerField()),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='receipt_processor.receipt')),
            ],
        ),
    ]
