version: "3.9" # optional since v1.27.0
services:
  # redis:
  #   image: redis
  #   command: redis-server
  # db:
  #   image: postgres:13.3
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   env_file:
  #     - ./.env
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    image: django_app
    # command: bash -c "python3 manage.py wait_for_database && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:3000"
    command: bash -c "python3 manage.py runserver 0.0.0.0:3000"
    # env_file:
    #   - ./.env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    # depends_on:
    #   - db
    #   - redis
    # depends_on:
    #   - db
    #   - redis
